name: Deploy Reuben code to production
version: 1.0.1

local:
  jobs:
    tests:
      name: Run tests
      commands:
        - rubocop <%= ENV['GIT_WORKING_DIR'] %>

    push:
      name: Push changes
      commands:
        - git checkout <%= ENV['GIT_BRANCH'] %>
        - git push

remote:
  before_job:
    description: Run command(s) before each remote job
    commands:
      - cd <%= ENV['REMOTE_ROOT_DIR'] %>

  jobs:
    stop_bot:
      name: Stop bot
      can_fail: true
      commands:
        - systemctl stop reuben

    pull:
      name: Pull changes
      commands:
        - git checkout <%= ENV['GIT_BRANCH'] %>
        - git pull
        - chmod 755 bin/build_image
        - chmod 755 bin/install_reuben
        - chmod 755 bin/install_gems
        - chmod 755 bin/reuben

    install_gems:
      name: Install gems
      commands:
        - bin/install_gems

    install_bot:
      name: Install bot
      if: test -f .env && echo false
      commands:
        - bin/install_reuben
        - bin/reuben --load-schema --no-logging

    start_bot:
      name: Start bot
      can_fail: true
      commands:
        - systemctl start reuben
